MAGIC = b"STEG"
VERSION = 1
NONCE_LEN = 12

MAGIC_LEN = 4
VERSION_LEN = 1
TOTAL_LEN_LEN = 4
HEADER_LEN = MAGIC_LEN + VERSION_LEN + TOTAL_LEN_LEN

CIPHERTEXT_LEN_LEN = 4
DEFAULT_DECODE_OUTPUT = "decoded_output.bin"

